### ISSUE TITLE
17mon数据库dump到txt，城市名称乱码

### ISSUE THREAD

**Issue by hnkeyang** [shuax/LocateIP#2]
以下是其中几个网段
43.243.228.4    43.243.228.7    中国 内蒙古乌冥ϯࠥ؃
43.243.228.8    43.243.228.11   中国 内蒙古巴徦׷ץД
43.243.228.12   43.243.228.19   中国 内蒙古呼佨ԴޥД

**Comment by shuax** [comment]
好的，我看看

**Comment by shuax** [comment]
`43.243.228.0    43.243.228.3    中国 内蒙古乌海`
`43.243.228.4    43.243.228.7    中国 内蒙古乌兰察布`
`43.243.228.8    43.243.228.11   中国 内蒙古巴彦淖尔`
`43.243.228.12   43.243.228.19   中国 内蒙古呼伦贝尔`
`43.243.228.20   43.243.228.23   中国 内蒙古通辽`
`43.243.228.24   43.243.228.27   中国 内蒙古赤峰`
`43.243.228.28   43.243.228.31   中国 内蒙古呼和浩特`
`43.243.228.32   43.243.228.43   中国 内蒙古呼伦贝尔`

我这边没问题，但是我修改了一下代码，可能是void*转换有问题吧。

**Comment by hnkeyang** [comment]
我之前是在Linux下编译有乱码， 修改完路径的版本，我看是windows格式的路径，我在windows编译了下没有乱码， 我又测试了修改路径之前的版本，在windows下编译也没有乱码

**Comment by shuax** [comment]
感谢反馈，已经修复。
