### ISSUE TITLE
最近有计划支持ipip最新的ipdb格式吗？

### ISSUE THREAD

**Issue by NakornC** [shuax/LocateIP#4]
2019年7月起，ipip只提供 IPDB格式的数据库
IDPB 解析代码地址：https://www.ipip.net/support/code.html

下面是免费版IP地址数据库20190703
[ipipfreedb.zip](https://github.com/shuax/LocateIP/files/3409237/ipipfreedb.zip)

**Comment by shuax** [comment]
老板，学不动了。从dat到datx到ipdb。
——————————
我研究一下吧。

**Comment by shuax** [comment]
学了下，没学会，不搞了。
